<?php
//$_SERVER['DOCUMENT_ROOT'] .
// $Id;


//---------------------------------- Страницы Магазина ---------------------------------------- 

//Всюду по Drupal, hook_help () используется, чтобы вывести справку текст наверху страниц. 
//Некоторые другие части страниц Drupal получают объяснительный текст от этих обработчиков прерываний также.
//Мы используем это здесь, чтобы иллюстрировать, как добавить текст справки к страницам, которые определяет
//Ваш модуль.

function lavalampmenu_help($section) {
	switch ($section) {
	case 'Lavalampmenu':
		// Вот некоторый текст справки для заказной страницы.
		return t('Этот текст из метода lavalampmenu_help.');
	}
}


/**
* A simple page callback.
*
* Возвратные вызовы страницы обязаны возвращать всю страницу. 
* Информационное наполнение тогда обычно выводится через звонок в тему ('страница'), 
* где система темы тогда окружит информационное наполнение в соответствующих блоках,
* передвижении, и моделировании.
*
* Если Вы не хотите использовать систему темы (например для того, чтобы вывести изображение или XML), 
* Вы должны напечатать информационное наполнение самостоятельно и не возвратить что-нибудь.
*/

/**
* Более сложный возвратный вызов страницы, который берет параметры.
*
* В параметрах передают от URL страницы. Они всегда - следующие элементы пути после местоположения страницы. 
* Из-за этого, если URL страницы перемещен позже, эта функция не должна быть изменена на accomodate перемещение. 
* Это - хорошая идея всегда обеспечить значения по умолчанию для параметров
*/

function lavalampmenu_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op){
    case 'list':
    $blocks[0] = array(
	    'info'       => 'lavalampmenu',
	    'status'     => TRUE,
        'weight'     => 0,
        'visibility' => 1,        
		'region'     => 'footer',
	);	
    return $blocks;
    case 'view':	   
	    switch ($delta) {
			case 0: $block = array('content' => lavalampmenu_contents(1),); return $block;						
		};
        
  }
}

function lavalampmenu_contents($which_block) {
  switch ($which_block) {
    case 1: 
	drupal_add_css(drupal_get_path('module', 'lavalampmenu') .'/js/lavalamp/lavalamp_test.css', 'module');
	drupal_add_js(drupal_get_path('module', 'lavalampmenu') .'/js/lavalamp/jquery.easing.min.js', 'module');
	drupal_add_js(drupal_get_path('module', 'lavalampmenu') .'/js/lavalamp/jquery.lavalamp.min.js', 'module');

	
	drupal_add_js('$(function() {$(".lavaLamp1").lavaLamp({fx: "easeOutQuad", speed: 500,returnDelay:1000});});', 'inline');
	return variable_get('lavalampmenu',  t(''));		
  }
}

function lavalampmenu_preprocess_page($variables) {  
	//меняем на более новую версию jquery	    
	//print_r(arg(0) == 'procat' &&   arg(1)=='concretGoods');
	//drupal_set_html_head('<meta content="'.arg(2).'" property="test">'); 
	//dpm(arg());
	if (arg(0)!='admin' && arg(2)!='edit'){
	        //dpm(arg(2));
	  	//drupal_set_html_head('<meta content="'.arg(2).'" property="test">');   
		$scripts = drupal_add_js();
		$new_jquery = array(drupal_get_path('module', 'procat') .'/js/jquery-1.7.1.min.js' => $scripts['core']['misc/jquery.js']);
		$scripts['core'] = array_merge($new_jquery, $scripts['core']);
		unset($scripts['core']['misc/jquery.js']);
		$variables['scripts'] = drupal_get_js('header', $scripts);
				
	}
}

//http://www.micro-system.org/
//http://news.yandex.ru/yandsearch?showdups=1&catnews=4&rpt=nnews2&within=7
//http://zoom.cnews.ru
//http://texnomaniya.ru/




	

